"""SINAS_API_KEY_FILE resolves into the field every consumer already reads.

The key can only be minted by a running Sinas instance, so it cannot be
generated by whatever deploys SGR — it has to be carried in. Supplying it as a
literal env var puts the value inside the deployment description (Pulumi state,
Helm values, CI config), which makes whoever can write there the only person
able to rotate it. Reading it from a file lets the platform hand the secret to
the container directly, so it never enters that description at all.

`sinas_api_key` is read directly in eight places (query_runner, bulk_pipeline,
faithfulness, citation_adjudicate, identity, sinas, answer_regress), so the
file is resolved INTO that field rather than exposed as a second one — none of
those call sites should have to know where the value came from.
"""

from __future__ import annotations

import pytest

from app.config import Settings


def test_file_is_read_into_the_key_field(tmp_path, monkeypatch):
    key = tmp_path / "sinas-api-key"
    key.write_text("sk-from-file")
    monkeypatch.delenv("SINAS_API_KEY", raising=False)
    monkeypatch.setenv("SINAS_API_KEY_FILE", str(key))

    assert Settings().sinas_api_key == "sk-from-file"


def test_trailing_newline_is_stripped(tmp_path, monkeypatch):
    # A mounted secret normally ends in a newline. Unstripped it rides into the
    # Authorization header and Sinas rejects the token as malformed — a 401
    # that looks like a bad key rather than a formatting bug.
    key = tmp_path / "sinas-api-key"
    key.write_text("sk-from-file\n")
    monkeypatch.delenv("SINAS_API_KEY", raising=False)
    monkeypatch.setenv("SINAS_API_KEY_FILE", str(key))

    assert Settings().sinas_api_key == "sk-from-file"


def test_literal_env_var_wins_over_the_file(tmp_path, monkeypatch):
    # An operator overriding a platform-mounted secret is deliberate. Silently
    # preferring the file would make that override look applied while doing
    # nothing.
    key = tmp_path / "sinas-api-key"
    key.write_text("sk-from-file")
    monkeypatch.setenv("SINAS_API_KEY", "sk-from-env")
    monkeypatch.setenv("SINAS_API_KEY_FILE", str(key))

    assert Settings().sinas_api_key == "sk-from-env"


def test_unreadable_path_fails_at_startup(tmp_path, monkeypatch):
    # Fatal, not a warning: booting with an empty key defers the failure to a
    # 401 from Sinas on the first background run, long after the cause is
    # visible and only under load.
    monkeypatch.delenv("SINAS_API_KEY", raising=False)
    monkeypatch.setenv("SINAS_API_KEY_FILE", str(tmp_path / "absent"))

    with pytest.raises(ValueError, match="could not be read"):
        Settings()


def test_empty_file_fails_at_startup(tmp_path, monkeypatch):
    # An empty mount is the shape a half-provisioned secret takes, and it would
    # otherwise pass validation as a blank key.
    key = tmp_path / "sinas-api-key"
    key.write_text("   \n")
    monkeypatch.delenv("SINAS_API_KEY", raising=False)
    monkeypatch.setenv("SINAS_API_KEY_FILE", str(key))

    with pytest.raises(ValueError, match="is empty"):
        Settings()


def test_neither_set_leaves_the_key_empty(monkeypatch):
    # `sinas` auth mode does not require the key at import time; the guards
    # that need it raise where it is used.
    monkeypatch.delenv("SINAS_API_KEY", raising=False)
    monkeypatch.delenv("SINAS_API_KEY_FILE", raising=False)

    assert Settings().sinas_api_key == ""
